using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class LevelLoader : MonoBehaviour
{

    [SerializeField] private string _sceneToLoadName;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter2D(Collider2D collider) 
    {
        Debug.Log("Player collided with a level loader.");
        GameObject collisionGameObject = collider.gameObject;
        SceneManager.LoadScene(_sceneToLoadName);
    }
}
